"""Creacion de tablas

Revision ID: 29284ea2da76
Revises: 
Create Date: 2025-10-15 15:52:23.729998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29284ea2da76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costos_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificador_producto', sa.VARCHAR(length=36), nullable=False),
    sa.Column('precio_compra', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificador_unico', sa.VARCHAR(length=36), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('precio', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('estado', postgresql.ENUM('inventario', 'vendido', name='estado_producto'), server_default='inventario', nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificador_unico')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_identificacion', sa.VARCHAR(length=50), nullable=False),
    sa.Column('contrasena', sa.VARCHAR(length=255), nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_identificacion')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificador_unico', sa.VARCHAR(length=36), nullable=False),
    sa.Column('nombre_producto', sa.VARCHAR(length=100), nullable=False),
    sa.Column('precio', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('fecha_venta', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('vendido_por', postgresql.ENUM('Lauren Vanegas', 'Juan Obando', name='vendido_por_enum'), nullable=True),
    sa.Column('metodo_pago', postgresql.ENUM('Efectivo', 'Nequi', name='metodo_pago_enum'), nullable=True),
    sa.Column('tipo_venta', postgresql.ENUM('Combo', 'Individual', name='tipo_venta_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificador_unico')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventas')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('costos_producto')
    # ### end Alembic commands ###
