"""crear tablas iniciales

Revision ID: def12a0f7896
Revises: 
Create Date: 2025-10-13 14:04:08.193573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def12a0f7896'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costosProducto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificador_producto', sa.String(length=36), nullable=False),
    sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificador_unico', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('inventario', 'vendido'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificador_unico')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_identificacion', sa.String(length=50), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_identificacion')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificador_unico', sa.String(length=36), nullable=False),
    sa.Column('nombre_producto', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_venta', sa.DateTime(), nullable=True),
    sa.Column('vendido_por', sa.Enum('Lauren Vanegas', 'Ximena Guerrero', 'Juan Guacaneme', 'Juan Obando', name='vendido_por_enum'), nullable=True),
    sa.Column('metodo_pago', sa.Enum('Efectivo', 'Nequi', name='metodo_pago_enum'), nullable=True),
    sa.Column('tipo_venta', sa.Enum('Combo', 'Individual', name='tipo_venta_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificador_unico')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventas')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('costosProducto')
    # ### end Alembic commands ###
